### ISSUE TITLE
When SSR is enabled in nuxt the icons have weird styling and adds extra padding or margin

### ISSUE THREAD

**Issue by batyr993** [ERPedersen/nuxt-mdi#2]
Hi,
I have project where I use **nuxt 3.8.2** along with **tailwindcss 3.4.1**
When I set **ssr to false** in **nuxt.config.ts** the icons have weird behavior. Extra spacing or padding is added making my navigation look unprofessional. When I set **ssr to true** then everything works as expected. I thought I was messing with my styling or so, but when I commented out my icons, then styling went back to normal.
# See the picture below with `ssr: false`  (unexpected behavior)
![Screenshot 2024-02-06 at 16 05 31](https://github.com/ERPedersen/nuxt-mdi/assets/43746237/bc4b9a85-3103-4b39-bf5d-26a0e8f39e42)
# When I enable ssr: (expected behavior)
![Screenshot 2024-02-06 at 16 09 59](https://github.com/ERPedersen/nuxt-mdi/assets/43746237/4b3f7901-8fbb-4ba6-94b8-b4133c6bbb72)
# My `nuxt.config.ts` file:
```
export default defineNuxtConfig({
  //@ts-ignore
  devtools: { enabled: true },
  srcDir: 'src/',
  ssr: false,
  css: ['./assets/css/main.css'],
  modules: ['@pinia/nuxt', 'nuxt-mdi', ['@nuxtjs/i18n', {
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected'
    },
    locales: availableLocales,
    lazy: true,
    langDir: 'translations/',
    defaultLocale: locale
  }]],
  mdi: {
    cache: false,
    componentName: 'MdiIcon',
    defaultSize: '1em'
  },
  pinia: {
    storesDirs: ['./stores/**'],
  },
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  }
})
```

# Here is how I use icons in my template (excerpt..)
```
...
<div class="absolute inset-y-0 left-0 flex items-center pointer-events-none">
      <MdiIcon :icon="subItem.icon" class="text-xl"></MdiIcon>
</div>
...
```

**Comment by ezmemoar** [comment]
got same issue here. Hope this one fixed asap.

**Comment by batyr993** [comment]
Thanks @ERPedersen for the fix!
